### ISSUE TITLE
Tagged release

### ISSUE THREAD

**Issue by RikSomers** [CachetHQ/Badger#1]
Hi,

Is it possible for a tagged release to be made?

We previously used the `alt-three/badger` package, but that has been deprecated:
`Package alt-three/badger is abandoned, you should avoid using it. Use cachethq/badger instead.`, however, this `cachethq/badger` repository has no tagged releases yet.

It is our policy to only use tagged releases of a repository so we can make sure everything works correctly with set versions of packages.

Thanks!

**Comment by GrahamCampbell** [comment]
Using the abandoned package should be fine until there is a stable release here. The packages are the same.

**Comment by RikSomers** [comment]
They are not the same tho as this package supports 5.8 (at least in `composer.json`) and `alt-three/badger` does not.

**Comment by MatasElectronics** [comment]
@GrahamCampbell Any news on this? What is holding you back to tag a release?

**Comment by jbrooksuk** [comment]
Released v3.0 (https://github.com/cachethq/badger/releases/tag/v3.0.0)
